version: "3.9"
services:
  backend:
    build: .
    image: iweddocker/apps-iwed:v1.0
    restart: always
    env file:
      - .env
    ports:
      - "3000"
    volumes:
      - app-data:/app/public/images

  web:
    build: ./nginx
    image: iweddocker/web-proxy
    restart: always
    ports:
    - "80:80"
    depends_on:
    - backend
volumes:
  app-data: