version: "3.9"
services:
  backend:
    build: .
    image: iweddocker/apps-iwed:v1.0
    restart: always
    ports:
      - "3000"
    volumes:
      - app-data:/app/public/images
 volumes:
  app-data: